export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCES = 'FETCH_POSTS_SUCCES';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const ADDING_POSTS_REQUEST = 'ADDING_POSTS_REQUEST';